# Login
az login

# Configurações
RG="rg-vm-gamer-br"
LOCATION="brazilsouth"
VM="VM-Gamer-BR"
VNET="vnet-gamer-br"
SUBNET="subnet-gamer"
NSG="nsg-rdp-br"
PUBLIC_IP="pip-gamer-br"
USER="gameradmin"
MY_IP="SEU_IP_PUBLICO/32"

# Grupo de recursos
az group create \
  --name $RG \
  --location $LOCATION

# Rede virtual
az network vnet create \
  --resource-group $RG \
  --name $VNET \
  --address-prefix 10.10.0.0/16 \
  --subnet-name $SUBNET \
  --subnet-prefix 10.10.1.0/24

# IP público estático
az network public-ip create \
  --resource-group $RG \
  --name $PUBLIC_IP \
  --location $LOCATION \
  --sku Standard \
  --allocation-method Static

# Grupo de segurança
az network nsg create \
  --resource-group $RG \
  --name $NSG

# Liberar RDP somente para seu IP
az network nsg rule create \
  --resource-group $RG \
  --nsg-name $NSG \
  --name Allow-RDP-My-IP \
  --priority 100 \
  --source-address-prefixes $MY_IP \
  --destination-port-ranges 3389 \
  --protocol Tcp \
  --access Allow \
  --direction Inbound

# Criar VM Windows
az vm create \
  --resource-group $RG \
  --name $VM \
  --location $LOCATION \
  --image Win2022Datacenter \
  --size Standard_D4s_v5 \
  --vnet-name $VNET \
  --subnet $SUBNET \
  --nsg $NSG \
  --public-ip-address $PUBLIC_IP \
  --public-ip-sku Standard \
  --admin-username $USER \
  --storage-sku Premium_LRS

# Mostrar IP
az vm list-ip-addresses \
  --resource-group $RG \
  --name $VM \
  --output table
