#!/bin/bash
VM="PC-Gamer"
DISK="pc-gamer.qcow2"
ISO="Windows.iso"
RAM="32G"
CPU="12"
SIZE="250G"
UEFI="/usr/share/OVMF/OVMF_CODE.fd"
qemu-img create -f qcow2 "$DISK" "$SIZE"
qemu-system-x86_64 \
-enable-kvm \
-machine q35,accel=kvm \
-name "$VM" \
-cpu host \
-smp "$CPU" \
-m "$RAM" \
-drive if=pflash,format=raw,readonly=on,file="$UEFI" \
-drive file="$DISK",if=none,id=nvme0,format=qcow2,cache=none,aio=native \
-device nvme,drive=nvme0,serial=PCVIRTUAL \
-cdrom "$ISO" \
-device virtio-net-pci,netdev=net0 \
-netdev user,id=net0 \
-device virtio-balloon-pci \
-device virtio-rng-pci \
-device usb-tablet \
-device virtio-vga \
-display gtk \
-boot order=d \
-no-reboot \
-monitor stdio \
-object iothread,id=iothread0 \
-device virtio-scsi-pci,id=scsi0,iothread=iothread0 \
-device virtio-serial-pci \
-device virtio-keyboard-pci \
-device virtio-mouse-pci \
-device virtio-rng-pci \
-audiodev driver=none,id=noaudio \
