az login

RG="rg-vm-br"
LOCATION="brazilsouth"
VM="vm-windows-br"
VNET="vnet-br"

az group create \
  --name $RG \
  --location $LOCATION

az network vnet create \
  --resource-group $RG \
  --name $VNET \
  --address-prefix 10.0.0.0/16 \
  --subnet-name default \
  --subnet-prefix 10.0.0.0/24

az vm create \
  --resource-group $RG \
  --name $VM \
  --location $LOCATION \
  --image Win2022Datacenter \
  --size Standard_D4s_v5 \
  --vnet-name $VNET \
  --subnet default \
  --admin-username gameradmin \
  --public-ip-sku Standard \
  --storage-sku Premium_LRS

az vm show \
  --resource-group $RG \
  --name $VM \
  --show-details
