name: RDP Workflow

on:
  workflow_dispatch:

jobs:
  windows-rdp:
    runs-on: windows-latest

    steps:
      - name: Atualizar sistema
        shell: powershell
        run: |
          Write-Host "Preparando Windows..."

      - name: Verificar RDP
        shell: powershell
        run: |
          Get-Service TermService
          Get-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Configurar ambiente
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path C:\RDP -Force
          Write-Host "Ambiente RDP preparado"

      - name: Informações da máquina
        shell: powershell
        run: |
          hostname
          systeminfo | Select-String "OS Name","OS Version"

      - name: Finalizar
        run: |
          echo "Workflow RDP concluído."
